<style>
	.explorer-section {
		width: 640px;
		max-width: calc(100vw - 80px);
		margin: 40px auto;
	}
	.explorer-section iframe {
		min-height: 360px;
	}
</style>

<br>
<br>
<br>
<hr style="max-width: 700px; margin: 0 auto;">
<br>

<section id="explorer" class="py-4">
	<header class="text-center prose mx-auto">
        <h1>
            Explore the data
            <span class="bg-green-400 rounded-lg text-sm text-white px-2 py-1">Beta</span>
        </h1>
		<p class="lead">
			This section will show you some of the rich data that Hyde is able to extract and generate from a simple Markdown post.
		</p>
		<p>
			Click on the code icon  next to a heading to see the source on GitHub.

			The mobile version of this section is still work in progress.
		</p>
    </header>

	<section class="explorer-section">
		<h2 class="text-2xl font-bold my-4">
			The Markdown Source

			<sup class="opacity-75 hover:opacity-100"><a href="https://github.com/hydephp/examples/blob/0b7fab1c7e4e51c9bac264aa06e57027d4bbb413/examples/semantic-html/alice-in-wonderland.md"><small><span style="color: #5fb3b3;">&lt;</span><span style="color: #eb606b;">Source</span><span style="color: #5fb3b3;">/&gt;</span></div></small></a></sup>
		</h2>
		<iframe width="100%" height="100%" src="https://desilva.se/cdn/gist/snippets/50c1336da708438e8fdd9fa5cf81ff0b/argon-alice-in-wonderland-markdown.html" frameborder="0"></iframe>
	</section>

	<section class="explorer-section">
		<h2 class="text-2xl font-bold my-4">
			The Compiled HTML
		</h2>
		<aside class="prose max-w-full">
			<table class="border"> <thead> <tr> <th colspan="2"> <details> <summary class="cursor-pointer px-3 pt-1"> Data parsed by <a href="https://validator.schema.org/">schema.org</a> </summary> <p class="font-normal px-4"> <strong>About the table:</strong> This table is one generated by the Schema.org Validator and shows the article data parsed by their system. This kind of content can show up in smart cards and search results and may help improve your SEO. </p> </details> </th> </tr> </thead> <tbody> <tr> <th> <div>@type</div> </th> <td> <div>Article</div> </td> </tr> <tr> <th> <div>@id</div> </th> <td> <div>http://schema.org/post-article</div> </td> </tr> <tr> <th> <div>identifier</div> </th> <td> <div>alice-in-wonderland</div> </td> </tr> <tr> <th> <div>headline</div> </th> <td> <div>Alice's Adventures in Wonderland</div> </td> </tr> <tr> <th> <div>dateCreated</div> </th> <td> <div>1865-11-18T18:52:00</div> </td> </tr> <tr> <th> <div>datePublished</div> </th> <td> <div>1865-11-18T18:52:00</div> </td> </tr> <tr> <th> <div>articleBody</div> </th> <td> <div>Alice was beginning to get very tired of sitting by her sister on the bank, and of having nothing to do...</div> </td> </tr> <tr> <th> <div>author/publisher</div> </th> <td></td> </tr> <tr> <th> <div>@type</div> </th> <td> <div>Person</div> </td> </tr> <tr> <th> <div>name</div> </th> <td> <div>Lewis Carroll</div> </td> </tr> </tbody> </table>
		</aside>
	</section>

	<section class="explorer-section">
		<h2 class="text-2xl font-bold my-4">
			The Compiled HTML

			<sup class="opacity-75 hover:opacity-100"><a href="https://github.com/hydephp/examples/blob/e319f0a24a14c07f9183735daa7e8eb3c255db57/examples/semantic-html/alice-in-wonderland.html"><small><span style="color: #5fb3b3;">&lt;</span><span style="color: #eb606b;">Source</span><span style="color: #5fb3b3;">/&gt;</span></div></small></a></sup>
		</h2>
		<p class="lead">Try switching the tabs using the radio buttons to see diffrent views.</p>
		<b>Coming soon.</b>
	</section>

		
</section>