@extends('hyde::layouts.app')
@section('content')

{{-- 
<!-- Gradient by https://hypercolor.dev/ -->
<header class="py-8 px-4 text-center bg-gradient-to-r from-pink-300 via-purple-300 to-indigo-400">
	<h1 class="text-2xl md:text-3-xl lg:text-4xl font-black text-slate-700 px-3 my-3">
		Hyde Dashboard
	</h1>
	<strong class="text-xl md:text-2xl text-slate-800 px-3">
		Quick Links to Hyde Projects
	</strong>
</header> --}}

<section class="py-16 px-4 text-center bg-gray-50">
	<h2 class="text-2xl md:text-3-xl lg:text-4xl font-black text-slate-700 px-3 my-3">
		Main Repositories
	</h2>

	<div class="flex flex-wrap justify-center max-w-7xl mx-auto my-4 lg:my-8">
		<div class="my-4 px-4 w-full md:w-1/2 xl:w-1/3 max-w-md">
			<article class="bg-white p-4 rounded-lg shadow-xl">
				<header>
					<h3 class="font-bold text-2xl text-left border-b mb-3 pb-3">The Hyde Template Repo</h3>
					<a href="https://github.com/hydephp/hyde">
						<img src="https://opengraph.githubassets.com/1/hydephp/hyde"
							alt="Open Graph Image Repository Preview">
					</a>
				</header>
				<div class="py-4 prose">
					<p class="lead">
						The main repo for creating new projects and contains Hyde/Framework as a dependency.
					</p>
					<a href="https://packagist.org/packages/hyde/hyde"><img style="display: inline; margin: 4px 2px;" src="https://img.shields.io/packagist/v/hyde/hyde" alt="Latest Version on Packagist"></a>
					<a href="https://github.com/hydephp/hyde/blob/master/LICENSE.md"><img style="display: inline; margin: 4px 2px;" src="https://img.shields.io/github/license/hydephp/hyde" alt="License"></a>
				
					<a href="https://github.com/hydephp/hyde/actions/workflows/tests.yml"><img style="display: inline; margin: 4px 2px;" src="https://github.com/hydephp/hyde/actions/workflows/tests.yml/badge.svg" alt="GitHub Actions Test Suite"></a>
					<a href="https://github.com/hydephp/hyde/actions/workflows/codeql-analysis.yml"><img style="display: inline; margin: 4px 2px;" src="https://github.com/hydephp/hyde/actions/workflows/codeql-analysis.yml/badge.svg" alt="GitHub Actions CodeQL Analysis"></a>
					<a href="https://github.styleci.io/repos/471485402?branch=master"><img style="display: inline; margin: 4px 2px;" src="https://github.styleci.io/repos/471485402/shield?branch=master" alt="StyleCI Status"></a>
				</div>
			</article>
		</div>

		<div class="my-4 px-4 w-full md:w-1/2 xl:w-1/3 max-w-md">
			<article class="bg-white p-4 rounded-lg shadow-xl">
				<header>
					<h3 class="font-bold text-2xl text-left border-b mb-3 pb-3">The Hyde Core Package</h3>
					<a href="https://github.com/hydephp/framework">
						<img src="https://opengraph.githubassets.com/1/hydephp/framework"
							alt="Open Graph Image Repository Preview">
					</a>
				</header>
				<div class="py-4 prose">
					<p class="lead">
						The core logic used for the Hyde Framework. Should be used together with Hyde/Hyde.
					</p>
					<a href="https://packagist.org/packages/hyde/framework"><img style="display: inline; margin: 4px 2px;" src="https://img.shields.io/packagist/dt/hyde/framework" alt="Total Downloads"></a>
					<a href="https://packagist.org/packages/hyde/framework"><img style="display: inline; margin: 4px 2px;" src="https://img.shields.io/packagist/v/hyde/framework" alt="Latest Version on Packagist"></a>
					<a href="https://github.com/hydephp/framework/blob/master/LICENSE.md"><img style="display: inline; margin: 4px 2px;" src="https://img.shields.io/github/license/hydephp/framework" alt="License"></a>
						<!-- Coverage data manually entered on 2022-03-28. Generated by PHPStorm with a result of 97% file cov & 85% line cov. -->
					<img style="display: inline; margin: 4px 2px;" src="https://img.shields.io/badge/coverage-85%25-yellowgreen" alt="Test Coverage" title="Test coverage generated 2022-03-28">
					<a href="https://github.styleci.io/repos/472503421?branch=master"><img style="display: inline; margin: 4px 2px;" src="https://github.styleci.io/repos/472503421/shield?branch=master" alt="StyleCI Status"></a>
				</div>
			</article>
		</div>

	</div>
</section>


@endsection