name: Build the site

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Create dotenv
      run: echo "SITE_URL=https://hydephp.github.io/" > .env
    
    - name: Add Torchlight token
      run: echo "TORCHLIGHT_TOKEN=${{ secrets.TORCHLIGHT_TOKEN }}" >> .env

    - name: Install composer dependencies
      run: composer install --prefer-dist

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Node dependencies
      run: npm install

    - name: Build frontend assets
      run: npm run prod


    - name: Run the Hyde Builder
      run: php hyde build --pretty


    - name: Create .nojekyll
      run: touch _site/.nojekyll

    - name: Create docs redirect
      run: echo '<meta http-equiv="refresh" content="0;url=/docs/master/index.html" />' > _site/docs/index.html

    # - name: Create readme
    # run: wget https://raw.githubusercontent.com/hydephp/hydephp.github.io/13f089c271c25fcc90730bd4c0c9772f4088e1c8/README.md -O _site/README.md

    - name: Push compiled files
      uses: cpina/github-action-push-to-another-repository@v1.4.2

      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: '_site'
        destination-github-username: 'hydephp'
        destination-repository-name: 'hydephp.github.io'
        target-branch: gh-pages
