# Run tests and build assets to ensure a consistent state between repositories
name: Test & Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        run: vendor/bin/pest

  build-hyde-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Hyde/Framework
        run: git clone https://github.com/hydephp/framework.git vendor/hyde/framework

      - name: Clean _media directory
        run: rm -rf _media && mkdir _media

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci
      - name: Build frontend files
        run: npm run prod

      - name: Upload app.css artifact
        uses: actions/upload-artifact@v3
        with:
          name: "app.css"
          path: "_media/app.css"

      - name: Upload hyde config directory artifact
        uses: actions/upload-artifact@v3
        with:
          name: "config"
          path: "vendor/hyde/framework/config"

  propagate-compiled-tailwind-to-hydefront:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build-hyde-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: hydephp/hydefront

      - name: Download app.css artifact
        uses: actions/download-artifact@v3
        with:
          name: app.css
          path: dist

      - name: Create pull request in HydeFront
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}

  create-hyde-merge-pull-request:
    needs: [run-tests, build-hyde-files]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clean _site directory
        run: rm -rf _site && mkdir _site

      - name: Clean _media directory
        run: rm -rf _media && mkdir _media

      - name: Download media artifact
        uses: actions/download-artifact@v3
        with:
          name: app.css
          path: _media
      
      - name: Download hyde config directory artifact
        uses: actions/download-artifact@v3
        with:
          name: config
          path: config
      
      - name: Create Pull Request with the new files
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automatic build update
          title: Update frontend and framework files
          body: Updated default app.css and cleaned the media directories and republished the configuration files.
          branch: update-hyde-assets
          base: ${{ github.head_ref }}
