name: Test Suite (Matrix)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hyde-tests:
    strategy:
      # fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
        extensions: fileinfo
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Set Framework version to dev-master
      run: composer require hyde/framework:dev-master
    - name: Set environment to testing
      run: echo "ENV=testing" > .env
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: vendor/bin/pest
      env: 
        ENV: testing
   